### ISSUE TITLE
probleme ChatBot-OpenIA

### ISSUE THREAD

**Issue by MartinBoulau** [webnexus-uk/ChatBot-OpenAI#3]
Hi! We got your project back and did some tests on it but we have a problem with character limits on the feedback messages. We modified the number of tokens but no noticeable change.

**Comment by webnexus-uk** [comment]
text-davinci-003 has a max token limit of 4,097 tokens.
If you would like to use the new GPT-3.5-turbo model checkout https://youtu.be/ty-FZfbI5zk
